### Create User
POST {{host}}/api/v{{version}}/User
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "email": "email@gmail.com",
  "password": "123456",
  "role": "Admin",
  "document": "12345678912",
  "birthDate": "1983-07-24",
  "phone": "11999999999",
  "address": "Av Reserva do Japy",
  "city": "Jundiaí",
  "state": "SP",
  "country": "Brazil",
  "zipCode": "13214-000"
}

> {%
    client.log(response.body);
    client.global.set("user_id", response.body.data);
%}


### Get All Users
GET {{host}}/api/v{{version}}/User
Authorization: Bearer {{auth_token}}


### Get User by Id
GET {{host}}/api/v{{version}}/User/{{user_id}}
Authorization: Bearer {{auth_token}}


### Update User 
PUT {{host}}/api/v{{version}}/User/{{user_id}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "id": "{{user_id}}",
  "email": "email@gmail.com",
  "password": "78945612",
  "role": "Admin",
  "document": "2145545654",
  "birthDate": "1985-01-30",
  "phone": "1195656565",
  "address": "Av Antonio Pincinato",
  "city": "Jundiaí",
  "state": "SP",
  "country": "Brazil",
  "zipCode": "13214-011"
}

### Delete User by Id
#DELETE {{host}}/api/v{{version}}/User/{{user_id}}
#Authorization: Bearer {{auth_token}}


