GET http://localhost:8085/api/Category

<> 2024-10-02T104433.200.json

###
POST http://localhost:8085/api/Category
Content-Type: application/json

{
  "name": "Category A"
}

<> 2024-10-02T104124.201.json

###
@id = 5f8d4e21-e5cc-4d70-9401-e1d112c3577e
PUT http://localhost:8085/api/Category/{{id}}
Content-Type: application/json

{
  "name": "Category Updated"
}

###
DELETE http://localhost:8085/api/Category/{{id}}

